# -*- coding: utf-8 -*-
"""Estudo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dy88p69jCCSiXbHjaw7RDwod5ap4fZIQ
"""

# Passo 1 - percor todos os arquivos da pasta base de dados (Pasta de Vendas)

import os
import pandas as pd
import plotly.express as px

lista_arquivo = os.listdir('/content/drive/MyDrive/Minicurso de Automação/Vendas')
display(lista_arquivo)

tabela_total = pd.DataFrame()

# Passo 2 - Importar as bases de dados de vendas

for arquivo in lista_arquivo:
    # se tem vendas no nome, então:
  if 'vendas' in arquivo.lower():

    # importar arquivo
    tabela = pd.read_csv(f'/content/drive/MyDrive/Minicurso de Automação/Vendas/{arquivo}')
    tabela_total = tabela_total.append(tabela)


# Passo 3 - Tratar as bases de dados
display(tabela_total)

# Passo 4 - Calcular o produto mais vendido em quantidade

tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[['Quantidade Vendida']].sort_values(by='Quantidade Vendida', ascending=True)
display(tabela_produtos)

# Passo 5 - Calcular produto que mais faturou

tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']
tabela_faturamento = tabela_total .groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[['Faturamento']].sort_values(by='Faturamento', ascending=True)
display(tabela_faturamento)

# Passo 6 - Calcular a loja que mais vendeu em faturamento - criar um grafico

tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas[['Faturamento']]
tabela_lojas = tabela_lojas[['Faturamento']].sort_values(by='Faturamento', ascending=True)
display(tabela_lojas)

grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()